# Generated by Django 4.2.3 on 2023-07-31 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("msg", models.TextField()),
                (
                    "id",
                    models.TextField(max_length=5, primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
