# Generated by Django 4.2.3 on 2023-08-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ct", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ("-date",)},
        ),
    ]
